// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: mySQLOptions.proto

package gensql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MySQLType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeName string   `protobuf:"bytes,1,opt,name=typeName,proto3" json:"typeName,omitempty"`
	Args     []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *MySQLType) Reset() {
	*x = MySQLType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mySQLOptions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MySQLType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLType) ProtoMessage() {}

func (x *MySQLType) ProtoReflect() protoreflect.Message {
	mi := &file_mySQLOptions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLType.ProtoReflect.Descriptor instead.
func (*MySQLType) Descriptor() ([]byte, []int) {
	return file_mySQLOptions_proto_rawDescGZIP(), []int{0}
}

func (x *MySQLType) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *MySQLType) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var file_mySQLOptions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*MySQLType)(nil),
		Field:         50000,
		Name:          "mySQLType",
		Tag:           "bytes,50000,opt,name=mySQLType",
		Filename:      "mySQLOptions.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional MySQLType mySQLType = 50000;
	E_MySQLType = &file_mySQLOptions_proto_extTypes[0]
)

var File_mySQLOptions_proto protoreflect.FileDescriptor

var file_mySQLOptions_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x79, 0x53, 0x51, 0x4c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x09, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x3a, 0x49, 0x0a, 0x09, 0x6d, 0x79, 0x53, 0x51, 0x4c, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x6d, 0x79, 0x53, 0x51, 0x4c, 0x54, 0x79, 0x70, 0x65, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x73, 0x71, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mySQLOptions_proto_rawDescOnce sync.Once
	file_mySQLOptions_proto_rawDescData = file_mySQLOptions_proto_rawDesc
)

func file_mySQLOptions_proto_rawDescGZIP() []byte {
	file_mySQLOptions_proto_rawDescOnce.Do(func() {
		file_mySQLOptions_proto_rawDescData = protoimpl.X.CompressGZIP(file_mySQLOptions_proto_rawDescData)
	})
	return file_mySQLOptions_proto_rawDescData
}

var file_mySQLOptions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mySQLOptions_proto_goTypes = []interface{}{
	(*MySQLType)(nil),                 // 0: MySQLType
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_mySQLOptions_proto_depIdxs = []int32{
	1, // 0: mySQLType:extendee -> google.protobuf.FieldOptions
	0, // 1: mySQLType:type_name -> MySQLType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mySQLOptions_proto_init() }
func file_mySQLOptions_proto_init() {
	if File_mySQLOptions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mySQLOptions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MySQLType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mySQLOptions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_mySQLOptions_proto_goTypes,
		DependencyIndexes: file_mySQLOptions_proto_depIdxs,
		MessageInfos:      file_mySQLOptions_proto_msgTypes,
		ExtensionInfos:    file_mySQLOptions_proto_extTypes,
	}.Build()
	File_mySQLOptions_proto = out.File
	file_mySQLOptions_proto_rawDesc = nil
	file_mySQLOptions_proto_goTypes = nil
	file_mySQLOptions_proto_depIdxs = nil
}
